### ISSUE TITLE
Plugin removed from Firefox Add-Ons

### ISSUE THREAD

**Issue by ned** [itayperl/jisho-ojad#4]
Looks like the link in the README (https://addons.mozilla.org/en-US/firefox/addon/jisho-ojad) no longer works and I can't see the add-on when searching the website.

**Comment by itayperl** [comment]
Yeah, the add-on was taken down due to a "security issue", namely that it copies raw HTML from the OJAD webpage into Jisho. They're technically in the right as this is considered bad practice in general... Though I think it's unlikely that the maintainers of OJAD will ever go out of their way to attack users of my add-on. :)

I'll fix it next time I have some time to kill.
Thanks for the heads up!

**Comment by itayperl** [comment]
Fixed.

**Comment by ned** [comment]
Legend, thank you, this makes a huge difference to my Japanese study :)
